rename file for `cargo publish` compatibility
This fixes the following problem with `cargo publish`:

```console
steveej@steveej-t480s-work ✓ ~/src/job-redhat/dkregistry-rs  355ae6e
$ cargo publish
    Updating crates.io index
   Packaging dkregistry v0.3.0 (/home/steveej/src/job-redhat/dkregistry-rs)
error: failed to prepare local package for uploading

Caused by:
  cannot package a filename with a special character `:`: tests/fixtures/quay.io_v2_openshift-release-dev_ocp-release_manifests_4.1.0-rc.9/sha256:cf85f02c014c5b46f8aa46242802c16b30a9be16fc0f595d22faf419a1cb731eP
```