v2/manifest: Explicitly enumerate re-exported items from manifest_schema2
There is a name conflict when re-exporting v2::Config alongside
v2::manifest::manifest_schema2::Config

This fixes this clippy error:

error: ambiguous glob re-exports
Error:   --> src/v2/manifest/mod.rs:12:9
   |
3  | use crate::v2::*;
   |     ------------ but the name `Config` in the type namespace is also re-exported here
...
12 | pub use self::manifest_schema2::*;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ the name `Config` in the type namespace is first re-exported here
   |
   = note: `-D ambiguous-glob-reexports` implied by `-D warnings`

error: could not compile `dkregistry` (lib) due to previous error